### ISSUE TITLE
NoSuchFlowExecutionException when trying to login

### ISSUE THREAD

**Issue by jonded94** [RobertKrajewski/Sync-my-L2P#118]
When trying to authenticate in L2P for giving the needed API permissions to Sync-my-L2P, I receive the following error message (part of it in German):

"Ein Fehler ist aufgetreten: NoSuchFlowExecutionException"

Steps:
1. I press on the "Login/Einloggen" Button in Sync-my-L2P
2. A new window with a progess bar and the text "Authentifizierung notwendig. Browser öffnet automatisch" pops up
3. A webrowser with the URL "https://sso.rwth-aachen.de/idp/profile/SAML2/Redirect/SSO?execution=e2s1" shows up, resulting in a webpage from the RWTH Single Login with the before mentioned error message "Ein Fehler ist aufgetreten: NoSuchFlowExecutionException".

I am using Linux, (K)ubuntu 18.04.

**Comment by jonded94** [comment]
@SebSdr 

Thanks, that is actually a way that works.

**Comment by justin-time** [comment]
Hi, unfortunately I can not reproduce this bug. But could you check out this native debian package for Ubuntu 18.04: https://github.com/RobertKrajewski/Sync-my-L2P/releases/download/v2.3.0/sync-my-l2p_2.3.0-0.bionic_amd64.deb

**Comment by jonded94** [comment]
Hey, thanks for your answer. I installed the .deb package, but unfortunately I face the same problem.
Is there any way I could provide you more information that you can use for reproducing this bug? It seems to only happen under Kubuntu, KDE Plasma.

**Comment by justin-time** [comment]
I think this is not a Sync-my-L2P bug. 
You can fix it by changing the default web browser: Go to  _System Settings → Applications → Web Browser and setting parameter Open http and https URLs_ and change the entry to "with the following command:" → and type the name of your browser e.g "firefox".

There is an problem with xdg-open in Kubuntu, because by using the KDE environment xdg-open uses [KIO](https://en.wikipedia.org/wiki/KIO) to check an URL before opening the web browser. And it looks like KIO does not work with the authorization link for Sync-my-L2P.

**Comment by jonded94** [comment]
@justin-time 
Thank you, that solved the problem. The error no longer occurs for me at all.

Do you happen to know how and where I could report that bug?
