### ISSUE TITLE
Windows file paths exceeding 260 characters

### ISSUE THREAD

**Issue by t-schroeder** [RobertKrajewski/Sync-my-L2P#138]
**Describe the bug**
Windows (every version except for Win10 and even that has it by default) has a max path limit of 260. That means the absolute path of a folder + the filename must not exceed 260 characters. Sync-my-L2P does not check if it would exceed that limit when downloading files. If it creates a file with a path that's too long, you can't open the file.

**To Reproduce**
1. In Moodle create a file resource via the "add activity" dialog and enter a name that's 255 characters long (maximum length that Moodle permits).
2. Sync it with Sync-my-L2P to a Windows machine.
3. Try to open it.

**Expected behavior**
You should be able to open the file.

**Screenshots**
![windows-file-max-path-exceeded](https://user-images.githubusercontent.com/24255259/55966278-631a2700-5c78-11e9-9c8a-230251bc0cc7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version v2.4.0

**Additional context**
There are no errors in the application's log.

**Comment by Tastaturtaste** [comment]
As presented in [the documentation](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) of the windows api filenames with up to 32767 characters are possible while using the unicode versions of winapi functions. As far as I can tell from the aforementioned documentation prefixing the filepath with "\\?\" should enable this functionality. It would be nice to enable this, since some files are named with ridiculously long names, preventing the download.
