### ISSUE TITLE
Skip folders for single files

### ISSUE THREAD

**Issue by t-schroeder** [RobertKrajewski/Sync-my-L2P#152]
For every "file" activity a separate folder is created. It's probably done this way because a "file" activity can contain multiple files so you went with the generic solution of always creating a folder with the name of the activity and downloading all files of the activity into that folder. This can cause path names to become unnecessarily long and working with the files becomes more tedious.

It would be nice if "file" activities that contain just a single file would be downloaded as just one file instead of as a folder with the file in it.

**Comment by RobertKrajewski** [comment]
Thanks for this suggestion. However, skipping the folders can create even worse problems due to file name conflicts. E.g. if every week a new file with the same name "exercise.pdf" is uploaded. An elegant solution to this problem, which is also user-friendly, is beyond my time constraints. However, I am open for suggestions including source code.
